name = "orcagym"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

main = ".vercel/output/static/_worker.js"

[assets]
directory = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages"
