const fs = require('fs');
let txt = fs.readFileSync('lib/supabase.ts', 'utf8');
let lines = txt.split('\n');

const replacementLines = [
  "          parent_name: p.name,",
  "          child_id: pChildren[0]?.id || p.id,",
  "          child_name: childNameStr,",
  "          hours_added: pay.purchased_hours || p.purchased_hours || 6,",
  "          course_name: 'Orca Cubs',",
  "          amount: pay.payment_amount ? Number(pay.payment_amount) : 4100,",
  "          slip_ref: pay.payment_ref_no || '20264587123654',",
  "          slip_url: pay.payment_slip || p.payment_slip,",
  "          bank_name: pay.payment_bank || p.payment_bank || 'ธนาคารกสิกรไทย (KBank)',",
  "          payer_name: pay.payment_payer_name || p.payment_payer_name || p.name,",
  "          note: idx === 0 ? 'สร้างบัญชีผู้ปกครองใหม่' : 'เติมโควต้า',",
  "          created_at: pay.payment_datetime || pay.created_at || new Date().toISOString()",
  "        });",
  "      });",
  "    });",
  "",
  "    setLocal(STORAGE_KEYS.AUDIT_LOGS, freshLogs);",
  "    if (isSupabaseConfigured && supabase && freshLogs.length > 0) {",
  "      try {",
  "        await supabase.from('audit_logs').insert(freshLogs);",
  "      } catch (err) {}",
  "    }",
  "    return freshLogs;",
  "  },",
  "",
  "  async getAuditLogs(): Promise<AuditLog[]> {",
  "    if (isSupabaseConfigured && supabase) {",
  "      const { data } = await supabase.from('audit_logs').select('*').order('created_at', { ascending: false });",
  "      if (data && data.length > 0) return data;",
  "    }",
  "    initLocalSeed();",
  "    return getLocal<AuditLog[]>(STORAGE_KEYS.AUDIT_LOGS, []);",
  "  },",
  "",
  "  async saveAuditLog(log: AuditLog): Promise<void> {",
  "    if (!log.created_at) {",
  "      log.created_at = new Date().toISOString();",
  "    }",
  "    if (isSupabaseConfigured && supabase) {",
  "      await supabase.from('audit_logs').insert([log]);",
  "    }",
  "    const logs = getLocal<AuditLog[]>(STORAGE_KEYS.AUDIT_LOGS, []);",
  "    logs.unshift(log);",
  "    setLocal(STORAGE_KEYS.AUDIT_LOGS, logs);",
  "  },",
  "",
  "  async getSlotQuotas(): Promise<Record<string, number>> {",
  "    if (isSupabaseConfigured && supabase) {",
  "      const { data } = await supabase.from('slot_quotas').select('*');",
  "      if (data) {",
  "        const res = {};",
  "        data.forEach(q => {",
  "          res[\\_\\] = q.quota;",
  "          if (q.course_name) {",
  "            res[\\_\_\\] = q.quota;",
  "          }",
  "        });",
  "        return res;",
  "      }",
  "    }",
  "    return getLocal(STORAGE_KEYS.QUOTAS, {});",
  "  },",
  "",
  "  async saveSlotQuota(date, timeSlot, quota, courseName) {",
  "    if (isSupabaseConfigured && supabase) {",
  "      await supabase.from('slot_quotas').upsert([{ booking_date: date, time_slot: timeSlot, quota, course_name: courseName }]);",
  "    }",
  "    const quotas = getLocal(STORAGE_KEYS.QUOTAS, {});",
  "    quotas[\\_\\] = quota;",
  "    if (courseName && courseName !== 'All Courses') {",
  "      quotas[\\_\_\\] = quota;",
  "      quotas[\\_\\] = quota;",
  "    } else {",
  "      quotas[\\_Orca Cubs_\\] = quota;",
  "      quotas[\\_Mega Orca_\\] = quota;",
  "      quotas[\\_\\] = quota;",
  "    }",
  "    setLocal(STORAGE_KEYS.QUOTAS, quotas);",
  "  },",
  "",
  "  async getCourses() {",
  "    initLocalSeed();",
  "    let courses = getLocal(STORAGE_KEYS.COURSES, []);",
  "    ",
  "    // Auto-fix corrupted courses",
  "    let modified = false;",
  "    courses.forEach(c => {",
  "      if (c.description && c.description.includes('เน€')) {",
  "        if (c.id === 'c_cubs') c.description = 'เปิดประตูสู่การเรียนรู้กับคลาส ORCA Cubs (สำหรับน้องๆ อายุ 6-10 ปี) คลาสเรียนพื้นฐานเบื้องต้นสำหรับเด็กๆ ที่ดีไซน์มาเพื่อเสริมสร้างทักษะทางร่างกายและการเคลื่อนไหวอย่างถูกวิธี สนุกสนาน สมวัย ปูพื้นฐานแน่นเพื่อให้พร้อมต่อยอดในระดับที่สูงขึ้นได้อย่างมั่นใจ';",
  "        if (c.id === 'c_mega') c.description = 'ต่อยอดทักษะสู่ความเป็นเลิศกับคลาส Mega ORCA (สำหรับเด็กอายุ 7-15 ปี) เหมาะสำหรับผู้ที่มีพื้นฐานยิมนาสติกมาแล้ว หรือต้องการพัฒนาทักษะแบบก้าวกระโดด เน้นความแข็งแรง ความยืดหยุ่นขั้นสูง และความอดทน พร้อมปูทางสู่การแข่งขันในอนาคต';",
  "        modified = true;",
  "      }"
];

// The break is at line 471 in my slice!
let outLines = lines.slice(0, 471).concat(replacementLines, lines.slice(484));
fs.writeFileSync('lib/supabase.ts', outLines.join('\n'), 'utf8');
console.log('Fixed');
